version: '3.5'
services:
  nginx:
    image: nginx:stable
    volumes:
    - ./nginx:/etc/nginx
    - ./ssl:/etc/ssl
    - ./www:/var/www
    ports:
    # - 80:80
    - 443:443
    networks:
    - felia-nginx
    restart: unless-stopped

networks:
  felia-nginx:
    name: felia-nginx-net

